# Generated by Django 4.1.6 on 2023-02-26 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_pengajuan', models.CharField(blank=True, help_text='nomor pengajuan akan terisi otomatis', max_length=50, unique=True)),
                ('nama_kegiatan', models.CharField(blank=True, max_length=50)),
                ('waktu_ajuan', models.DateField(blank=True, null=True)),
                ('penanggung_jawab', models.CharField(blank=True, max_length=30, null=True)),
                ('total_ajuan', models.DecimalField(decimal_places=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='DanaMasuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dana_masuk', models.CharField(max_length=50)),
                ('waktu_masuk', models.DateField(null=True)),
                ('penanggung_jawab', models.CharField(max_length=30, null=True)),
                ('total_dana', models.DecimalField(decimal_places=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='RekapAjuanPengambilanTabungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_RAPT', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('jumlah', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RekapPencairanCek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_RPC', models.CharField(max_length=20, unique=True)),
                ('jumlah', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitAjuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_ajuan', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BuktiKasKeluar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_BKK', models.CharField(blank=True, help_text='nomor BKK akan terisi otomatis', max_length=50, unique=True)),
                ('tanggal_BKK', models.DateField(null=True)),
                ('dibayarkan_kepada', models.CharField(max_length=20)),
                ('uraian', models.CharField(max_length=50)),
                ('kode_bank', models.CharField(max_length=20)),
                ('nomer_cek', models.CharField(max_length=20)),
                ('ajuan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajuan.ajuan')),
            ],
        ),
        migrations.AddField(
            model_name='ajuan',
            name='RAPT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajuan.rekapajuanpengambilantabungan'),
        ),
        migrations.AddField(
            model_name='ajuan',
            name='RPC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajuan.rekappencairancek'),
        ),
        migrations.AddField(
            model_name='ajuan',
            name='unit_ajuan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajuan.unitajuan'),
        ),
    ]
