# Generated by Django 4.1.6 on 2023-05-01 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajuan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTertarik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer_bank_tertarik', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Bank Tertarik',
            },
        ),
        migrations.AlterModelOptions(
            name='ajuan',
            options={'verbose_name_plural': 'Ajuan'},
        ),
        migrations.AlterModelOptions(
            name='buktikaskeluar',
            options={'verbose_name_plural': 'Bukti Kas Keluar'},
        ),
        migrations.AlterModelOptions(
            name='danamasuk',
            options={'verbose_name_plural': 'Dana Masuk'},
        ),
        migrations.AlterModelOptions(
            name='rekapajuanpengambilantabungan',
            options={'verbose_name_plural': 'RAPT'},
        ),
        migrations.AlterModelOptions(
            name='rekappencairancek',
            options={'verbose_name_plural': 'RPC'},
        ),
        migrations.AlterModelOptions(
            name='unitajuan',
            options={'verbose_name_plural': 'Unit Ajuan'},
        ),
        migrations.RemoveField(
            model_name='ajuan',
            name='RPC',
        ),
        migrations.RemoveField(
            model_name='buktikaskeluar',
            name='kode_bank',
        ),
        migrations.AlterField(
            model_name='ajuan',
            name='nomor_pengajuan',
            field=models.CharField(blank=True, help_text='nomor pengajuan akan terisi otomatis', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='buktikaskeluar',
            name='no_BKK',
            field=models.CharField(blank=True, help_text='nomor BKK akan terisi otomatis', max_length=50),
        ),
        migrations.AlterField(
            model_name='rekapajuanpengambilantabungan',
            name='no_RAPT',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rekappencairancek',
            name='no_RPC',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Cek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_cek', models.CharField(max_length=50, null=True)),
                ('keterangan', models.CharField(max_length=50, null=True)),
                ('RPC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajuan.rekappencairancek')),
                ('ajuan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajuan.ajuan')),
                ('nomer_bank_tertarik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajuan.banktertarik')),
            ],
            options={
                'verbose_name_plural': 'Cek',
            },
        ),
        migrations.AddField(
            model_name='buktikaskeluar',
            name='nomer_bank_tertarik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajuan.banktertarik'),
        ),
        migrations.AlterField(
            model_name='buktikaskeluar',
            name='nomer_cek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajuan.cek'),
        ),
    ]
