# Generated by Django 4.1.6 on 2023-09-06 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajuan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTertarik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer_bank_tertarik', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Bank Tertarik',
            },
        ),
        migrations.CreateModel(
            name='Cek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(null=True)),
                ('no_cek', models.CharField(max_length=50, null=True)),
                ('keterangan', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cek',
            },
        ),
        migrations.AlterModelOptions(
            name='ajuan',
            options={'verbose_name_plural': 'Ajuan'},
        ),
        migrations.AlterModelOptions(
            name='buktikaskeluar',
            options={'verbose_name_plural': 'Bukti Kas Keluar'},
        ),
        migrations.AlterModelOptions(
            name='danamasuk',
            options={'verbose_name_plural': 'Dana Masuk'},
        ),
        migrations.AlterModelOptions(
            name='rekapajuanpengambilantabungan',
            options={'verbose_name_plural': 'RAPT'},
        ),
        migrations.AlterModelOptions(
            name='rekappencairancek',
            options={'verbose_name_plural': 'RPC'},
        ),
        migrations.AlterModelOptions(
            name='unitajuan',
            options={'verbose_name_plural': 'Unit Ajuan'},
        ),
        migrations.RenameField(
            model_name='danamasuk',
            old_name='nama_dana_masuk',
            new_name='uraian',
        ),
        migrations.RemoveField(
            model_name='ajuan',
            name='RPC',
        ),
        migrations.RemoveField(
            model_name='buktikaskeluar',
            name='kode_bank',
        ),
        migrations.RemoveField(
            model_name='danamasuk',
            name='penanggung_jawab',
        ),
        migrations.AlterField(
            model_name='ajuan',
            name='nama_kegiatan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ajuan',
            name='nomor_pengajuan',
            field=models.CharField(blank=True, help_text='nomor pengajuan akan terisi otomatis', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ajuan',
            name='total_ajuan',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='buktikaskeluar',
            name='no_BKK',
            field=models.CharField(blank=True, help_text='nomor BKK akan terisi otomatis', max_length=50),
        ),
        migrations.AlterField(
            model_name='rekapajuanpengambilantabungan',
            name='no_RAPT',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rekappencairancek',
            name='no_RPC',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unitajuan',
            name='unit_ajuan',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='RekapBankTertarik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_RBT', models.CharField(blank=True, help_text='nomor RBT akan terisi otomatis', max_length=50)),
                ('tanggal', models.DateField(null=True)),
                ('uraian', models.TextField()),
                ('dana_keluar', models.DecimalField(decimal_places=0, max_digits=20)),
                ('ajuan', models.ManyToManyField(to='ajuan.ajuan')),
                ('dana_masuk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajuan.danamasuk')),
                ('no_cek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajuan.cek')),
            ],
            options={
                'verbose_name_plural': 'Rekap Bank Tertarik',
            },
        ),
        migrations.AddField(
            model_name='cek',
            name='RPC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajuan.rekappencairancek'),
        ),
        migrations.AddField(
            model_name='cek',
            name='ajuan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ceks_utama', to='ajuan.ajuan'),
        ),
        migrations.AddField(
            model_name='cek',
            name='ajuan_terkait',
            field=models.ManyToManyField(blank=True, default='Masih Kosong', related_name='ceks_terkait', to='ajuan.ajuan'),
        ),
        migrations.AddField(
            model_name='cek',
            name='nomer_bank_tertarik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajuan.banktertarik'),
        ),
        migrations.AddField(
            model_name='buktikaskeluar',
            name='nomer_bank_tertarik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajuan.banktertarik'),
        ),
        migrations.AddField(
            model_name='danamasuk',
            name='bank_penerima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajuan.banktertarik'),
        ),
        migrations.AlterField(
            model_name='buktikaskeluar',
            name='nomer_cek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajuan.cek'),
        ),
    ]
