# Generated by Django 4.1.6 on 2023-02-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajuan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buktikaskeluar',
            name='no_BKK',
            field=models.CharField(blank=True, help_text='nomor BKK akan terisi otomatis', max_length=50),
        ),
        migrations.AlterField(
            model_name='rekappencairancek',
            name='no_RPC',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
