# Generated by Django 4.1.6 on 2023-09-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajuan', '0002_banktertarik_cek_alter_ajuan_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cek',
            name='ajuan',
        ),
        migrations.RemoveField(
            model_name='cek',
            name='keterangan',
        ),
        migrations.RemoveField(
            model_name='rekapbanktertarik',
            name='ajuan',
        ),
        migrations.RemoveField(
            model_name='rekapbanktertarik',
            name='uraian',
        ),
        migrations.AlterField(
            model_name='cek',
            name='ajuan_terkait',
            field=models.ManyToManyField(blank=True, related_name='ceks_terkait', to='ajuan.ajuan'),
        ),
    ]
