# Generated by Django 4.1.6 on 2023-05-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajuan', '0002_banktertarik_alter_ajuan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cek',
            name='total_ajuan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
