# Generated by Django 4.1.6 on 2023-05-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajuan', '0003_cek_total_ajuan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cek',
            name='total_ajuan',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
