# Generated by Django 4.1.6 on 2023-09-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajuan', '0003_remove_cek_ajuan_remove_cek_keterangan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cek',
            name='total_cek',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True),
        ),
    ]
