# Generated by Django 4.1.6 on 2023-09-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajuan', '0004_cek_total_cek'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajuan',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cek',
            name='ajuan_terkait',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_selected': False}, related_name='ceks_terkait', to='ajuan.ajuan'),
        ),
        migrations.AlterField(
            model_name='cek',
            name='total_cek',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
    ]
