# Generated by Django 4.1.6 on 2023-09-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajuan', '0005_ajuan_is_selected_alter_cek_ajuan_terkait_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cek',
            name='ajuan_terkait',
            field=models.ManyToManyField(blank=True, related_name='ceks_terkait', to='ajuan.ajuan'),
        ),
    ]
