# Generated by Django 4.1.6 on 2023-10-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajuan', '0006_alter_cek_ajuan_terkait'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banktertarik',
            options={'verbose_name_plural': 'Bank'},
        ),
        migrations.AddField(
            model_name='rekappencairancek',
            name='tanggal',
            field=models.DateField(null=True),
        ),
    ]
