# Generated by Django 4.1.6 on 2023-10-17 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajuan', '0007_alter_banktertarik_options_rekappencairancek_tanggal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rekappencairancek',
            name='tanggal',
        ),
    ]
