# Generated by Django 4.1.6 on 2023-10-17 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajuan', '0008_remove_rekappencairancek_tanggal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RekapBankTertarik',
        ),
    ]
