# Generated by Django 4.1.6 on 2023-11-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajuan', '0009_delete_rekapbanktertarik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danamasuk',
            name='uraian',
            field=models.TextField(max_length=50),
        ),
    ]
